# ML-04 — Search Intelligence Data Contract

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

One row represents the daily performance of a content item for a client on a specific report date.

Time window:
- Start date: 2026-06-01
- End date: 2026-06-30

The sample contains 11,694,072 rows. I also verified that some (report_date, client_hash_id, content_hash_id) combinations appear more than once, so the sample includes duplicate records.

In [14]:
con.sql("""
SELECT
    report_date,
    client_hash_id,
    content_hash_id,
    COUNT(*) AS rows
FROM read_parquet(
    'hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance_sample.parquet'
)
GROUP BY
    report_date,
    client_hash_id,
    content_hash_id
HAVING COUNT(*) > 1
LIMIT 10;
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  report_date           client_hash_id           content_hash_id  rows
0  2026-06-13  client_1a730cb2640a1abf  content_0a21add649629840     2
1  2026-06-13  client_1a730cb2640a1abf  content_0ffd552a735a66ab     2
2  2026-06-13  client_1a730cb2640a1abf  content_f85822ce54f90378     2
3  2026-06-13  client_1a730cb2640a1abf  content_ff51845ed161bfb4     2
4  2026-06-13  client_1a730cb2640a1abf  content_8f5be8e45452dda7     2
5  2026-06-13  client_1a730cb2640a1abf  content_a4990373223aa784     2
6  2026-06-13  client_1a730cb2640a1abf  content_b5aec9a8a2ee7fb0     2
7  2026-06-13  client_1a730cb2640a1abf  content_c426957b8369a333     2
8  2026-06-13  client_1a730cb2640a1abf  content_5ea66e7cd969a440     2
9  2026-06-13  client_1a730cb2640a1abf  content_62a6c7628cfd006f     2

In [15]:
con.sql("""
SELECT
    MIN(report_date) AS start_date,
    MAX(report_date) AS end_date,
    COUNT(*) AS total_rows
FROM read_parquet(
    'hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance_sample.parquet'
);
""").df()

  start_date   end_date  total_rows
0 2026-06-01 2026-06-30    11694072

In [16]:
con.sql("""
SELECT *
FROM read_parquet(
    'hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance_sample.parquet'
)
WHERE report_date='2026-06-13'
AND client_hash_id='client_1a730cb2640a1abf'
AND content_hash_id='content_0a21add649629840';
""").df()

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2026-06-13,client_1a730cb2640a1abf,content_0a21add649629840,True,True,False,False,0,0,0,...,0,0,0,0,0,0,0,0,0,2026-06
1,2026-06-13,client_1a730cb2640a1abf,content_0a21add649629840,True,True,False,False,0,0,0,...,0,0,0,0,0,0,0,0,0,2026-06

In [17]:
from google.colab import userdata

token = userdata.get("HF_TOKEN")
print("Token loaded successfully!" if token else "Token not found!")

Token loaded successfully!

In [18]:
!pip -q install datasets huggingface_hub duckdb pyarrow

In [19]:
import duckdb
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

con = duckdb.connect()

con.execute(f"""
CREATE SECRET hf_secret (
    TYPE HUGGINGFACE,
    TOKEN '{HF_TOKEN}'
);
""")

print("Hugging Face secret configured successfully!")

Hugging Face secret configured successfully!

In [20]:
from huggingface_hub import list_repo_files

files = list_repo_files(
    repo_id="FlyRank/internship-warehouse",
    repo_type="dataset",
    token=HF_TOKEN
)

for f in files[:100]:
    print(f)

.gitattributes
README.md
dim_clients.parquet
dim_content.parquet
fact_content_daily_performance/month=2025-01/data_0.parquet
fact_content_daily_performance/month=2025-02/data_0.parquet
fact_content_daily_performance/month=2025-03/data_0.parquet
fact_content_daily_performance/month=2025-04/data_0.parquet
fact_content_daily_performance/month=2025-05/data_0.parquet
fact_content_daily_performance/month=2025-06/data_0.parquet
fact_content_daily_performance/month=2025-07/data_0.parquet
fact_content_daily_performance/month=2025-08/data_0.parquet
fact_content_daily_performance/month=2025-09/data_0.parquet
fact_content_daily_performance/month=2025-10/data_0.parquet
fact_content_daily_performance/month=2025-11/data_0.parquet
fact_content_daily_performance/month=2025-12/data_0.parquet
fact_content_daily_performance/month=2026-01/data_0.parquet
fact_content_daily_performance/month=2026-02/data_0.parquet
fact_content_daily_performance/month=2026-03/data_0.parquet
fact_content_daily_performance/month=2026-04/data_0.parquet
fact_content_daily_performance/month=2026-05/data_0.parquet
fact_content_daily_performance/month=2026-06/data_0.parquet
fact_content_daily_performance_sample.parquet
fact_content_query_90d.parquet

In [21]:
con.sql("""
SELECT *
FROM read_parquet(
    'hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance_sample.parquet'
)
LIMIT 5
""").df()

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2026-06-01,client_3ffa76342f366962,content_1a6296faee432dae,True,True,False,False,0,0,0,...,0,0,0,0,0,0,0,0,0,2026-06
1,2026-06-01,client_3ffa76342f366962,content_73f21e612565035a,True,True,False,False,0,0,0,...,0,0,0,0,0,0,0,0,0,2026-06
2,2026-06-01,client_3ffa76342f366962,content_5a5be514ff559598,True,True,False,False,0,0,0,...,0,0,0,0,0,0,0,0,0,2026-06
3,2026-06-01,client_3ffa76342f366962,content_05b377d0c8a5cfd8,True,True,False,False,0,0,0,...,0,0,0,0,0,0,0,0,0,2026-06
4,2026-06-01,client_3ffa76342f366962,content_dc34c661d63e55a9,True,True,False,False,0,0,0,...,0,0,0,0,0,0,0,0,0,2026-06

In [22]:
df = con.sql("""
SELECT *
FROM read_parquet(
    'hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance_sample.parquet'
)
LIMIT 1
""").df()

print(df.columns.tolist())

['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events', 'month']

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

## Features
- gsc_impressions
- gsc_clicks
- gsc_avg_position
- ga4_pageviews
- ga4_sessions

## Label
- No explicit label exists in this sample. If building a predictive model, a future performance metric (e.g., future clicks or impressions) would need to be created separately.

## Context
- report_date
- client_hash_id
- content_hash_id
- month
- client_has_gsc
- client_has_ga4
- gsc_data_available
- ga4_data_available

## Excluded
- ai_chatgpt, ai_perplexity, ai_gemini, ai_copilot, ai_claude, ai_meta, ai_other
  - Reason: These are traffic-source details and are not required for the basic feature set.

- scroll_events
  - Reason: Not directly related to search performance prediction.

- sessions_direct
- sessions_social
- sessions_referral
- sessions_paid
  - Reason: These represent non-search traffic sources.

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [23]:
con.sql("""
SELECT
    MIN(report_date) AS start_date,
    MAX(report_date) AS end_date,
    COUNT(*) AS total_rows
FROM read_parquet(
    'hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance_sample.parquet'
);
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  start_date   end_date  total_rows
0 2026-06-01 2026-06-30    11694072

In [24]:
con.sql("""
SELECT
    report_date,
    client_hash_id,
    content_hash_id,
    COUNT(*) AS rows
FROM read_parquet(
    'hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance_sample.parquet'
)
GROUP BY
    report_date,
    client_hash_id,
    content_hash_id
HAVING COUNT(*) > 1
LIMIT 10;
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  report_date           client_hash_id           content_hash_id  rows
0  2026-06-13  client_1a730cb2640a1abf  content_1a0c3a8cc6bdd5bc     2
1  2026-06-13  client_1a730cb2640a1abf  content_8d5a5293688d7d8e     2
2  2026-06-13  client_1a730cb2640a1abf  content_b40e27e07768f907     2
3  2026-06-13  client_1a730cb2640a1abf  content_965b9031838c130f     2
4  2026-06-13  client_1a730cb2640a1abf  content_fa351551b6d49870     2
5  2026-06-13  client_1a730cb2640a1abf  content_6604767cde89152e     2
6  2026-06-13  client_1a730cb2640a1abf  content_f58b50fc3b086cc2     2
7  2026-06-13  client_1a730cb2640a1abf  content_aaacc6b4d641648b     2
8  2026-06-13  client_1a730cb2640a1abf  content_42239c7e1161beee     2
9  2026-06-13  client_1a730cb2640a1abf  content_0e6cbd7d714dda07     2

In [25]:
con.sql("""
SELECT
    SUM(CASE WHEN gsc_data_available = FALSE THEN 1 ELSE 0 END) AS gsc_missing,
    SUM(CASE WHEN ga4_data_available = FALSE THEN 1 ELSE 0 END) AS ga4_missing
FROM read_parquet(
    'hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance_sample.parquet'
);
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   gsc_missing  ga4_missing
0    7815135.0    8651918.0

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

## Data limits

- This sample covers data only for the period from 2026-06-01 to 2026-06-30.
- The sample contains duplicate records for some combinations of report_date, client_hash_id, and content_hash_id.
- Some records have GSC or GA4 data marked as unavailable.
- Client and content identifiers are hashed, so they cannot be mapped back to the original identities.
- The sample dataset may not contain all historical or production data available in the complete warehouse.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

Yes. Every major contract statement is supported by SQL queries and their outputs in this notebook, including the time window, duplicate check, and data availability.